<a href="https://colab.research.google.com/github/dibkb/tensorflow-udemy/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning the fundamentals of tensorflow

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.14.0


In [5]:
# Creating tensors
scaler = tf.constant(9)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [7]:
# Check dimensions
scaler.ndim

0

In [10]:
# matrix dimensions
matrix = tf.constant([[1,2],
                     [2,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4]], dtype=int32)>

In [11]:
matrix.ndim

2

In [14]:
# flaot_matrix
matrixTwo = tf.constant([
    [3.0,4],
    [3,4.4],
    [4,5]
],dtype = tf.float16)
matrixTwo

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3. , 4. ],
       [3. , 4.4],
       [4. , 5. ]], dtype=float16)>