<a href="https://colab.research.google.com/github/dibkb/tensorflow-udemy/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning the fundamentals of tensorflow

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.14.0


In [5]:
# Creating tensors
scaler = tf.constant(9)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [7]:
# Check dimensions
scaler.ndim

0

In [10]:
# matrix dimensions
matrix = tf.constant([[1,2],
                     [2,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4]], dtype=int32)>

In [11]:
matrix.ndim

2

In [16]:
# flaot_matrix
matrixTwo = tf.constant([
    [3.0,4,3.0],
    [3,4.4,3],
    [4,5,1]
],dtype = tf.float16)
matrixTwo
matrixTwo.ndim

2

In [23]:
# Random tensors
randomOne = tf.random.Generator.from_seed(42)
randomOne =randomOne.normal(shape=(3,4))
randomOne

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [27]:
randomTwo = tf.random.shuffle(randomOne)
randomTwo

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [28]:
onesTensor = tf.ones(shape=(4,9))
onesTensor

<tf.Tensor: shape=(4, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

# **From Numpy**

In [34]:
import numpy as np
npArray = np.arange(1,31)
npArray.shape
tensorNp = tf.constant(npArray,shape=(5,2,3))
tensorNp

<tf.Tensor: shape=(5, 2, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30]]])>